version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: atine-test-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9001:80"
    php-fpm:
      build: docker/php-fpm
      container_name: atine-test-php
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini